flasksong/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from flask_wtf.file import FileAllowed, FileField

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    song = FileField('Upload Your Song', validators=[DataRequired(), FileAllowed(['mp3'])])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    commnt = StringField('Comment', validators=[DataRequired()])
    submit = SubmitField('Comment')
    
    

flasksong/main/routes.py
from flask import render_template, request, Blueprint, flash
from flasksong.models import Post, Comments_on_post
from flasksong.posts.forms import CommentForm
from flask_login import current_user
from flasksong import db

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home", methods=['GET', 'POST'])
def home():
	page = request.args.get('page', 1, type=int)
	post_id = request.args.get('post_id', type=int)
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
	comments_model = Comments_on_post.query.order_by(Comments_on_post.date_posted.desc())
	form = CommentForm()
	#likes = Likes_comments.query
	if form.validate_on_submit() and current_user.is_authenticated:
		comments_on_post_obj = Comments_on_post(comments=form.commnt.data, author=current_user, postID=post_id)
		db.session.add(comments_on_post_obj)
		db.session.commit()
		flash('Your comment has been submitted!', 'success')
		
	return render_template('home.html', form=form, posts=posts, comments_model=comments_model)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

flasksong/posts/routes.py
from flask import render_template, url_for, flash, request, redirect, abort, Blueprint
from flask_login import current_user, login_required
from flasksong import db
from flasksong.models import Post
from flasksong.posts.forms import PostForm
from flasksong.posts.utils import save_song


posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.song.data:
            song_file_temp = save_song(form.song.data)
            #current_user.song_file = song_file
        post = Post(title=form.title.data, song_file=song_file_temp, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
	post = Post.query.get_or_404(post_id)
	return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	form = PostForm()
	if form.validate_on_submit():
		if form.song.data:
			song_file_temp = save_song(form.song.data)
		post.title = form.title.data
		post.song_file = song_file_temp
		db.session.commit()
		flash('Your post has been Updated!', 'success')
		return redirect(url_for('posts.post', post_id=post.id))
	elif request.method == 'GET':
		form.title.data = post.title
	return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('Your post has been deleted!', 'success')
	return redirect(url_for('main.home'))


@posts.route("/likes_incr/<int:post_id>")
@login_required
def likes_incr(post_id):
	post = Post.query.get_or_404(post_id)
	post.likes = post.likes + 1
	db.session.commit()
	#flash('You like it', 'success')
	return redirect(request.referrer)

flasksong/users/routes.py
from flask import render_template, url_for, flash, request, redirect, Blueprint
from flasksong import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from flasksong.models import User, Post, Followers_following
from flasksong.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flasksong.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    #user = User.query.filter_by(username=username).first_or_404()
    followerss = Followers_following.query.filter_by(user_id=current_user.id).all()
    foll=len(followerss)
    followerss = Followers_following.query.filter_by(followers=current_user.username).all()
    foll2=len(followerss)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form, foll=foll, foll2=foll2)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    followerss = Followers_following.query.filter_by(user_id=user.id).all()
    foll=len(followerss)
    followerss = Followers_following.query.filter_by(followers=user.username).all()
    foll2=len(followerss)
    return render_template('user_posts.html', posts=posts, user=user, foll=foll, foll2=foll2)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user) 
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)



@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None: 
        flash('Invalid or Expired token', 'warning')
        return redirect(url_for('users.reset_request'))   
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your Password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/user/<string:username>/follower_follow")
@login_required
def follower_follow(username):
    user = User.query.filter_by(username=username).first_or_404()
    already_register_user = Followers_following.query.filter(Followers_following.followers == current_user.username)\
                            .filter(Followers_following.user_id == user.id)\
                            .all()
    #already_register_user2 = Followers_following.query.filter_by().first()
    if not already_register_user:
        followers_following_obj = Followers_following(followers=current_user.username, author=user)
        db.session.add(followers_following_obj)
        db.session.commit()
        flash('You follow', 'success')
    else:
        flash('You already follow', 'success')
    return redirect(url_for('main.home'))
    

flasksong/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flasksong/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
          <h4 class="mb-3">Followers - {{foll }} Following - {{foll2 }}</h4>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flasksong/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.song.label() }}
                    {{ form.song(class="form-control-file") }}
                    {% if form.song.errors %}
                        {% for error in form.song.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flasksong/templates/home.html
{% extends "layout.html" %}
{% block content %}

    {% for post in posts.items %}
        <article class="media content-section">
		<img class="article-image account-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-3" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%b %d %Y  %-I:%-M %p') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
             <div class="article-metadata">
       	      <div class="ready-player-{{loop.index}} player" style="width: 100%;">
		       <audio crossorigin >
				<source src="{{ url_for('static', filename='user_songs/' + post.song_file) }}">
		       </audio>
		      </div>
		 	 </div>
		<div class="article-metadata">
			<div class="col-sm-4 col-sm-offset-4">
		 		{{ post.likes }} likes
			</div>
		</div>
		

		<div class="article-metadata">
			<div class="container">
			  <div class="row">
			    <div class="col-sm">
			      <a class="mr-2" href="{{ url_for('posts.likes_incr', post_id=post.id) }}"><span id="cmnt-sec">Like</span></a>
			    </div>
			  </div>
			</div>		
		</div>
		
	{% for cm in comments_model %}		
		{% if cm.postID ==  post.id%}
			
		 <br>
		 <div class="row small-gap-row-below">
			<div class="col-xs-3 col-sm-1">
		         <img class="article-image comment-img" src="{{ url_for('static', filename='profile_pics/' + cm.author.image_file) }}">
			</div>		
		<div class="col-xs-9 col-sm-11">
		   <div id="ip2" class="rounded float-left" style="background-color:#F2F5FF">
		    <a class="mr-2" href="{{ url_for('users.user_posts', username=cm.author.username) }}">{{ cm.author.username }}</a>
		    <span>{{ cm.comments }}<span>
		   </div><br>
		   <div>
		    <small class="text-muted">Like</small> -
		    <small class="text-muted">Reply</small> -	
		    <small class="text-muted">{{ cm.date_posted.strftime('%d-%m-%Y') }}</small>
		   </div> 
	    </div>

		</div>
			 			
		{% endif %}
	{% endfor %}	
	<form method="POST" action="{{ url_for('main.home', post_id=post.id) }}">
      {{ form.hidden_tag() }}		 		        
        <fieldset class="form-group">		        
            {% if form.commnt.errors %}
                {{ form.commnt(id="ip4") }}
                <div class="invalid-feedback">
                    {% for error in form.commnt.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.commnt(id="ip4") }}
		
        	{{ form.submit(class="btn inputGroup-sizing-sm") }}
    		
            {% endif %}
        	</div>	 
	 	</fieldset>		
      </form>
    </article>
	
    {% endfor %}
	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
	{% endfor %}
{% endblock content %}

flasksong/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/greghub/green-audio-player/dist/css/green-audio-player.min.css">

    {% if title %}
        <title>Flask Song - {{ title }}</title>
    {% else %}
        <title>Flask Song</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Song</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <script src="https://cdn.jsdelivr.net/gh/greghub/green-audio-player/dist/js/green-audio-player.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            GreenAudioPlayer.init({
                selector: '.player',
                stopOthersOnPlay: true
            });
        });
    </script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flasksong/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flasksong/templates/post.html
{% extends "layout.html" %}
{% block content %}

	<article class="media content-section">
	 <img class="rounded-circle article-image" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
	  <div class="media-body">
	    <div class="article-metadata">
	      <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
	      <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y %X') }}</small>
		{% if post.author == current_user  %}
			<div>
		        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
		    
			</div>
		{% endif %}
	    </div>
	    <h2 class="article-title"> {{ post.title }}</h2>
		   <div class="article-metadata">
       	     <div class="ready-player player" style="width: 100%;">
		      <audio crossorigin >
				<source src="{{ url_for('static', filename='user_songs/' + post.song_file) }}">
		      </audio>
		     </div>
		 </div>
	   <!-- <p class="article-content">{{ post.content }}</p> -->
	  </div>
	</article>
{% endblock content %}

flasksong/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

flasksong/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flasksong/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
  <div class="media">
    <img class="rounded-circle account-img" src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}">
    <div class="media-body">
      <h2 class="account-heading">{{ user.username }}</h2>
      <p class="text-secondary">{{ user.email }}</p>
      <h4 class="mb-3">Followers - {{foll }} Following - {{foll2 }}</h4>
  {% if user.username != current_user.username %}
    <a class="btn btn-info mb-2" href="{{ url_for('users.follower_follow', username=user.username) }}">Follow</a>
  {% endif %}
    </div>
  </div>
 
 	<h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
		      <div class="media-body">
          <div class="article-metadata">
            <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y %X') }}</small>
          </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
		         <div class="article-metadata">
              <div class="ready-player-{{loop.index}} player" style="width: 100%;">
               <audio crossorigin >
                <source src="{{ url_for('static', filename='user_songs/' + post.song_file) }}">
               </audio>
              </div>
             </div>
        </article>
    {% endfor %}
	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
	{% endfor %}
{% endblock content %}